
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.0"

executor: KubernetesExecutor
fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
webserverSecretKey: "ShouldNotBeInProduction"

scheduler:
  replicas: 2

webserver:
  replicas: 2
  readinessProbe:
    initialDelaySeconds: 45
  livenessProbe:
    initialDelaySeconds: 60

# Airflow Triggerer Config
triggerer:
  enabled: true
  # Number of airflow triggerers in the deployment
  replicas: 1

statsd:
  uid: null

pgbouncer:
  uid: null

redis:
  uid: null

dags:
  persistence:
    enabled: false
  gitSync:
    uid: null
    enabled: true
    repo: https://github.com/sameerameduri/airflow-on-openshift
    branch: main
    subPath: dags

scheduler:
    ## the number of scheduler Pods to run
    replicas: 1

    ## resource requests/limits for the scheduler Pods
    ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 2
        memory: 2Gi     
    logCleanup:
      enabled: false
      retentionMinutes: 21600

    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md
    livenessProbe:
      enabled: true

      ## configs for an additional check that ensures tasks are being created by the scheduler
      ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md
      taskCreationCheck:
        enabled: false
        thresholdSeconds: 300
        schedulerAgeBeforeCheck: 180


workers:
  replicas: 2
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 1
      memory: 1Gi

logs:
  persistence:
    enabled: true
    existingClaim: airflow-pvc
    accessMode: ReadWriteMany


flower:
  enabled: false

# ingress:
#   web:
#     enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
