
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.0"

executor: KubernetesExecutor
fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
webserverSecretKey: "ShouldNotBeInProduction"

scheduler:
  replicas: 2

webserver:
  replicas: 2
  readinessProbe:
    initialDelaySeconds: 45
  livenessProbe:
    initialDelaySeconds: 60

statsd:
  uid: null

pgbouncer:
  uid: null

redis:
  uid: null

dags:
  persistence:
    enabled: false
  gitSync:
    uid: null
    enabled: true
    repo: https://github.com/sameerameduri/airflow-on-openshift
    branch: main
    subPath: dags

logs:
  persistence:
    enabled: true

  scheduler:
  logCleanup:
    ## WARNING: must be disabled if `logs.persistence.enabled` is `true`
    enabled: false

    ## the number of minutes to retain log files (by last-modified time)
    retentionMinutes: 5

    ## the number of seconds between each check for files to delete
    intervalSeconds: 9


flower:
  enabled: false

# ingress:
#   web:
#     enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
