airflow:
  executor: CeleryExecutor
  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
  webserverSecretKey: "ShouldNotBeInProduction"

scheduler:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi
  logCleanup:
    enabled: false
    retentionMinutes: 2
  livenessProbe:
    enabled: true
    taskCreationCheck:
      enabled: false
      thresholdSeconds: 300
      schedulerAgeBeforeCheck: 180

web:
  replicas: 2
  readinessProbe:
    initialDelaySeconds: 45
  livenessProbe:
    initialDelaySeconds: 60

workers:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 1
      memory: 1Gi
  logCleanup:
    enabled: false
    retentionMinutes: 2

# Airflow Triggerer Config
triggerer:
  enabled: true
  replicas: 1

statsd:
  uid: null

pgbouncer:
  uid: null

redis:
  uid: null

dags:
  persistence:
    enabled: false
  gitSync:
    uid: null
    enabled: true
    repo: https://github.com/sameerameduri/airflow-on-openshift
    branch: main
    subPath: dags


logs:
  persistence:
    enabled: true
    existingClaim: airflow-pvc


flower:
  enabled: false

# ingress:
#   web:
#     enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
