
defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.7.0"

executor: KubernetesExecutor
fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
webserverSecretKey: "ShouldNotBeInProduction"

scheduler:
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 2Gi

workers:
  replicas: 2
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 1
      memory: 1Gi

webserver:
  replicas: 2
  readinessProbe:
    initialDelaySeconds: 45
  livenessProbe:
    initialDelaySeconds: 60

# Airflow Triggerer Config
triggerer:
  enabled: true
  replicas: 1

statsd:
  uid: null

pgbouncer:
  uid: null

redis:
  uid: null

dags:
  persistence:
    enabled: false
  gitSync:
    uid: null
    enabled: true
    repo: https://github.com/sameerameduri/airflow-on-openshift
    branch: main
    subPath: dags


logs:
  persistence:
    enabled: false
    existingClaim: airflow-pvc


flower:
  enabled: false

# ingress:
#   web:
#     enabled: true

postgresql:
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
