
airflow:
  
  airflow:
    fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
    webserverSecretKey: "ShouldNotBeInProduction"
    legacyCommands: false
    executor: CeleryExecutor
    defaultAirflowRepository: apache/airflow
    defaultAirflowTag: "2.7.0"

  scheduler:
    replicas: 1
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 2
        memory: 2Gi
    logCleanup:
        enabled: false
        retentionMinutes: 5
    livenessProbe:
        enabled: true
        taskCreationCheck:
          enabled: false
          thresholdSeconds: 300
          schedulerAgeBeforeCheck: 180

  workers:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: 1
          memory: 3Gi
        requests:
          cpu: 1
          memory: 1Gi
      logCleanup:
        enabled: false
        retentionMinutes: 5


  # Airflow Triggerer Config
  triggerer:
    enabled: true
    replicas: 1

  logs:
      persistence:
        enabled: true
        existingClaim: airflow-pvc

  dags:
      path: /opt/airflow/dags
      gitSync:
        enabled: true
        repo: "https://github.com/sameerameduri/airflow-on-openshift"
        branch: main
        subPath: dags

  statsd:
    uid: null

  pgbouncer:
    uid: null

  redis:
    uid: null


  flower:
    enabled: false

# ingress:
#   web:
#     enabled: true

  postgresql:
    primary:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
