{{- if .Values.userVars.demo_install.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ (printf "%s-scc" .Release.Name) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.userVars.scc.clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{- end }}